(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
From Jasmin Require Import word.

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

Require Import Hacspec_concordium.
Export Hacspec_concordium.

Class t_HasChainMetadata (Self : choice_type) := {
  f_slot_time_loc : {fset Location} ;
  f_slot_time : forall {L1 I1}, both L1 I1 (Self) -> both (L1 :|: f_slot_time_loc) I1 (t_Timestamp) ;
}.
Hint Unfold f_slot_time_loc.

Class t_HasParameter (Self : choice_type) := {
  f_size_loc : {fset Location} ;
  f_size : forall {L1 I1}, both L1 I1 (Self) -> both (L1 :|: f_size_loc) I1 (int32) ;
}.
Hint Unfold f_size_loc.
