(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
From Jasmin Require Import word.

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

Require Import Super.
Export Super.

Class t_ContextType (Self : choice_type) := {
}.

#[global] Program Instance t_InitContextExtern_t_ContextType : t_ContextType t_InitContextExtern :=
  _.
Fail Next Obligation.
Hint Unfold t_InitContextExtern_t_ContextType.

#[global] Program Instance t_ReceiveContextExtern_t_ContextType : t_ContextType t_ReceiveContextExtern :=
  _.
Fail Next Obligation.
Hint Unfold t_ReceiveContextExtern_t_ContextType.
