(* File automatically generated by Hacspec *)
From Hacspec Require Import Hacspec_Lib MachineIntegers.
From Coq Require Import ZArith.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.

Require Import Hacspec_concordium.
Export Hacspec_concordium.

Require Import SeekFrom.
Export SeekFrom.

Require Import ContractState.
Export ContractState.

Require Import Logger.
Export Logger.

Require Import trap.
Export trap.
