[package]
name = "curve25519"
version = "0.1.0"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
edition = "2021"

[lib]
path = "src/curve25519.rs"

[dependencies]
num-bigint = "0.4"
natmod = { path = "../natmod" }

[dev-dependencies]
criterion = "0.4"
hex = "0.4"
rand = "0.8"
