(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
From Jasmin Require Import word.

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

Require Import Hacspec_lib.
Export Hacspec_lib.

Notation "'t_Block'" := (nseq int8 BLOCK_SIZE).
Definition Block {L : {fset Location}} {I : Interface} : both L I (t_Block) -> both L I (t_Block) :=
  id.

Notation "'t_Hash'" := (nseq int32 8).
Definition Hash {L : {fset Location}} {I : Interface} : both L I (t_Hash) -> both L I (t_Hash) :=
  id.

Notation "'t_OpTableType'" := (nseq int32 12).
Definition OpTableType {L : {fset Location}} {I : Interface} : both L I (t_OpTableType) -> both L I (t_OpTableType) :=
  id.

Notation "'t_RoundConstantsTable'" := (nseq int32 K_SIZE).
Definition RoundConstantsTable {L : {fset Location}} {I : Interface} : both L I (t_RoundConstantsTable) -> both L I (t_RoundConstantsTable) :=
  id.

Notation "'t_Sha256Digest'" := (nseq int8 HASH_SIZE).
Definition Sha256Digest {L : {fset Location}} {I : Interface} : both L I (t_Sha256Digest) -> both L I (t_Sha256Digest) :=
  id.

(*Not implemented yet? todo(item)*)

Equations v_BLOCK_SIZE {L : {fset Location}} {I : Interface} : both L I (uint_size) :=
  v_BLOCK_SIZE  :=
    solve_lift (ret_both (64 : uint_size)) : both L I (uint_size).
Fail Next Obligation.

Equations v_HASH_SIZE {L : {fset Location}} {I : Interface} : both L I (uint_size) :=
  v_HASH_SIZE  :=
    solve_lift ((ret_both (256 : uint_size)) ./ (ret_both (8 : uint_size))) : both L I (uint_size).
Fail Next Obligation.

Equations v_K_SIZE {L : {fset Location}} {I : Interface} : both L I (uint_size) :=
  v_K_SIZE  :=
    solve_lift (ret_both (64 : uint_size)) : both L I (uint_size).
Fail Next Obligation.

Equations v_LEN_SIZE {L : {fset Location}} {I : Interface} : both L I (uint_size) :=
  v_LEN_SIZE  :=
    solve_lift (ret_both (8 : uint_size)) : both L I (uint_size).
Fail Next Obligation.

Equations v_OP_TABLE {L : {fset Location}} {I : Interface} : both L I (t_OpTableType) :=
  v_OP_TABLE  :=
    OpTableType (array_from_list [solve_lift (ret_both (2 : uint_size));
      solve_lift (ret_both (13 : uint_size));
      solve_lift (ret_both (22 : uint_size));
      solve_lift (ret_both (6 : uint_size));
      solve_lift (ret_both (11 : uint_size));
      solve_lift (ret_both (25 : uint_size));
      solve_lift (ret_both (7 : uint_size));
      solve_lift (ret_both (18 : uint_size));
      solve_lift (ret_both (3 : uint_size));
      solve_lift (ret_both (17 : uint_size));
      solve_lift (ret_both (19 : uint_size));
      solve_lift (ret_both (10 : uint_size))]) : both L I (t_OpTableType).
Fail Next Obligation.

Equations ch {L1 : {fset Location}} {L2 : {fset Location}} {L3 : {fset Location}} {I1 : Interface} {I2 : Interface} {I3 : Interface} (x : both L1 I1 (t_U32)) (y : both L2 I2 (t_U32)) (z : both L3 I3 (t_U32)) : both (L1 :|: L2 :|: L3) (I1 :|: I2 :|: I3) (t_U32) :=
  ch x y z  :=
    solve_lift ((x .& y) .^ ((f_not x) .& z)) : both (L1 :|: L2 :|: L3) (I1 :|: I2 :|: I3) (t_U32).
Fail Next Obligation.

Equations maj {L1 : {fset Location}} {L2 : {fset Location}} {L3 : {fset Location}} {I1 : Interface} {I2 : Interface} {I3 : Interface} (x : both L1 I1 (t_U32)) (y : both L2 I2 (t_U32)) (z : both L3 I3 (t_U32)) : both (L1 :|: L2 :|: L3) (I1 :|: I2 :|: I3) (t_U32) :=
  maj x y z  :=
    solve_lift ((x .& y) .^ ((x .& z) .^ (y .& z))) : both (L1 :|: L2 :|: L3) (I1 :|: I2 :|: I3) (t_U32).
Fail Next Obligation.

Definition tmp_loc : Location :=
  (t_U32;0%nat).
Equations sigma {L1 : {fset Location}} {L2 : {fset Location}} {L3 : {fset Location}} {I1 : Interface} {I2 : Interface} {I3 : Interface} (x : both L1 I1 (t_U32)) (i : both L2 I2 (uint_size)) (op : both L3 I3 (uint_size)) : both (L1 :|: L2 :|: L3 :|: fset [tmp_loc]) (I1 :|: I2 :|: I3) (t_U32) :=
  sigma x i op  :=
    letb (tmp : t_U32) loc(tmp_loc) := impl__U32__rotate_right x (v_OP_TABLE.a[(((ret_both (3 : uint_size)) .* i) .+ (ret_both (2 : uint_size)))]) in
    letb _ := ifb op =.? (ret_both (0 : uint_size))
    then assign todo(term)
    else () in
    solve_lift (((impl__U32__rotate_right x (v_OP_TABLE.a[((ret_both (3 : uint_size)) .* i)])) .^ (impl__U32__rotate_right x (v_OP_TABLE.a[(((ret_both (3 : uint_size)) .* i) .+ (ret_both (1 : uint_size)))]))) .^ tmp) : both (L1 :|: L2 :|: L3 :|: fset [tmp_loc]) (I1 :|: I2 :|: I3) (t_U32).
Fail Next Obligation.

Definition s_loc : Location :=
  (t_RoundConstantsTable;1%nat).
Equations schedule {L1 : {fset Location}} {I1 : Interface} (block : both L1 I1 (t_Block)) : both (L1 :|: fset [s_loc;tmp_loc]) I1 (t_RoundConstantsTable) :=
  schedule block  :=
    letb b := impl__Block__to_be_U32s block in
    letb s loc(s_loc) := impl__RoundConstantsTable__new (ret_both (tt : 'unit)) in
    letb _ := foldi_both_list (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := v_K_SIZE))) (fun i =>
      ssp (fun _ =>
        solve_lift (ifb i <.? (ret_both (16 : uint_size))
        then letb _ := assign todo(term) in
        ret_both (tt : 'unit)
        else letb t16 := s.a[(i .- (ret_both (16 : uint_size)))] in
        letb t15 := s.a[(i .- (ret_both (15 : uint_size)))] in
        letb t7 := s.a[(i .- (ret_both (7 : uint_size)))] in
        letb t2 := s.a[(i .- (ret_both (2 : uint_size)))] in
        letb s1 := sigma t2 (ret_both (3 : uint_size)) (ret_both (0 : uint_size)) in
        letb s0 := sigma t15 (ret_both (2 : uint_size)) (ret_both (0 : uint_size)) in
        letb _ := assign todo(term) in
        ret_both (tt : 'unit)) : both (*2*)(L1:|:fset [s_loc;tmp_loc]) (I1) ('unit))) (ret_both (tt : 'unit)) in
    solve_lift s : both (L1 :|: fset [s_loc;tmp_loc]) I1 (t_RoundConstantsTable).
Fail Next Obligation.

Equations v_HASH_INIT {L : {fset Location}} {I : Interface} : both L I (t_Hash) :=
  v_HASH_INIT  :=
    Hash (array_from_list [U32 (solve_lift (ret_both (1779033703 : int32)));
      U32 (solve_lift (ret_both (3144134277 : int32)));
      U32 (solve_lift (ret_both (1013904242 : int32)));
      U32 (solve_lift (ret_both (2773480762 : int32)));
      U32 (solve_lift (ret_both (1359893119 : int32)));
      U32 (solve_lift (ret_both (2600822924 : int32)));
      U32 (solve_lift (ret_both (528734635 : int32)));
      U32 (solve_lift (ret_both (1541459225 : int32)))]) : both L I (t_Hash).
Fail Next Obligation.

Equations v_K_TABLE {L : {fset Location}} {I : Interface} : both L I (t_RoundConstantsTable) :=
  v_K_TABLE  :=
    RoundConstantsTable (array_from_list [U32 (solve_lift (ret_both (1116352408 : int32)));
      U32 (solve_lift (ret_both (1899447441 : int32)));
      U32 (solve_lift (ret_both (3049323471 : int32)));
      U32 (solve_lift (ret_both (3921009573 : int32)));
      U32 (solve_lift (ret_both (961987163 : int32)));
      U32 (solve_lift (ret_both (1508970993 : int32)));
      U32 (solve_lift (ret_both (2453635748 : int32)));
      U32 (solve_lift (ret_both (2870763221 : int32)));
      U32 (solve_lift (ret_both (3624381080 : int32)));
      U32 (solve_lift (ret_both (310598401 : int32)));
      U32 (solve_lift (ret_both (607225278 : int32)));
      U32 (solve_lift (ret_both (1426881987 : int32)));
      U32 (solve_lift (ret_both (1925078388 : int32)));
      U32 (solve_lift (ret_both (2162078206 : int32)));
      U32 (solve_lift (ret_both (2614888103 : int32)));
      U32 (solve_lift (ret_both (3248222580 : int32)));
      U32 (solve_lift (ret_both (3835390401 : int32)));
      U32 (solve_lift (ret_both (4022224774 : int32)));
      U32 (solve_lift (ret_both (264347078 : int32)));
      U32 (solve_lift (ret_both (604807628 : int32)));
      U32 (solve_lift (ret_both (770255983 : int32)));
      U32 (solve_lift (ret_both (1249150122 : int32)));
      U32 (solve_lift (ret_both (1555081692 : int32)));
      U32 (solve_lift (ret_both (1996064986 : int32)));
      U32 (solve_lift (ret_both (2554220882 : int32)));
      U32 (solve_lift (ret_both (2821834349 : int32)));
      U32 (solve_lift (ret_both (2952996808 : int32)));
      U32 (solve_lift (ret_both (3210313671 : int32)));
      U32 (solve_lift (ret_both (3336571891 : int32)));
      U32 (solve_lift (ret_both (3584528711 : int32)));
      U32 (solve_lift (ret_both (113926993 : int32)));
      U32 (solve_lift (ret_both (338241895 : int32)));
      U32 (solve_lift (ret_both (666307205 : int32)));
      U32 (solve_lift (ret_both (773529912 : int32)));
      U32 (solve_lift (ret_both (1294757372 : int32)));
      U32 (solve_lift (ret_both (1396182291 : int32)));
      U32 (solve_lift (ret_both (1695183700 : int32)));
      U32 (solve_lift (ret_both (1986661051 : int32)));
      U32 (solve_lift (ret_both (2177026350 : int32)));
      U32 (solve_lift (ret_both (2456956037 : int32)));
      U32 (solve_lift (ret_both (2730485921 : int32)));
      U32 (solve_lift (ret_both (2820302411 : int32)));
      U32 (solve_lift (ret_both (3259730800 : int32)));
      U32 (solve_lift (ret_both (3345764771 : int32)));
      U32 (solve_lift (ret_both (3516065817 : int32)));
      U32 (solve_lift (ret_both (3600352804 : int32)));
      U32 (solve_lift (ret_both (4094571909 : int32)));
      U32 (solve_lift (ret_both (275423344 : int32)));
      U32 (solve_lift (ret_both (430227734 : int32)));
      U32 (solve_lift (ret_both (506948616 : int32)));
      U32 (solve_lift (ret_both (659060556 : int32)));
      U32 (solve_lift (ret_both (883997877 : int32)));
      U32 (solve_lift (ret_both (958139571 : int32)));
      U32 (solve_lift (ret_both (1322822218 : int32)));
      U32 (solve_lift (ret_both (1537002063 : int32)));
      U32 (solve_lift (ret_both (1747873779 : int32)));
      U32 (solve_lift (ret_both (1955562222 : int32)));
      U32 (solve_lift (ret_both (2024104815 : int32)));
      U32 (solve_lift (ret_both (2227730452 : int32)));
      U32 (solve_lift (ret_both (2361852424 : int32)));
      U32 (solve_lift (ret_both (2428436474 : int32)));
      U32 (solve_lift (ret_both (2756734187 : int32)));
      U32 (solve_lift (ret_both (3204031479 : int32)));
      U32 (solve_lift (ret_both (3329325298 : int32)))]) : both L I (t_RoundConstantsTable).
Fail Next Obligation.

Definition h_loc : Location :=
  (t_Hash;2%nat).
Equations shuffle {L1 : {fset Location}} {L2 : {fset Location}} {I1 : Interface} {I2 : Interface} (ws : both L1 I1 (t_RoundConstantsTable)) (hashi : both L2 I2 (t_Hash)) : both (L1 :|: L2 :|: fset [h_loc;tmp_loc]) (I1 :|: I2) (t_Hash) :=
  shuffle ws hashi  :=
    letb h loc(h_loc) := hashi in
    letb _ := foldi_both_list (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := v_K_SIZE))) (fun i =>
      ssp (fun _ =>
        letb a0 := h.a[(ret_both (0 : int32))] in
        letb b0 := h.a[(ret_both (1 : int32))] in
        letb c0 := h.a[(ret_both (2 : int32))] in
        letb d0 := h.a[(ret_both (3 : int32))] in
        letb e0 := h.a[(ret_both (4 : int32))] in
        letb f0 := h.a[(ret_both (5 : int32))] in
        letb g0 := h.a[(ret_both (6 : int32))] in
        letb (h0 : t_U32) := h.a[(ret_both (7 : int32))] in
        letb t1 := (((h0 .+ (sigma e0 (ret_both (1 : uint_size)) (ret_both (1 : uint_size)))) .+ (ch e0 f0 g0)) .+ (v_K_TABLE.a[i])) .+ (ws.a[i]) in
        letb t2 := (sigma a0 (ret_both (0 : uint_size)) (ret_both (1 : uint_size))) .+ (maj a0 b0 c0) in
        letb _ := assign todo(term) in
        letb _ := assign todo(term) in
        letb _ := assign todo(term) in
        letb _ := assign todo(term) in
        letb _ := assign todo(term) in
        letb _ := assign todo(term) in
        letb _ := assign todo(term) in
        letb _ := assign todo(term) in
        solve_lift (ret_both (tt : 'unit)) : both (*2*)(L1:|:L2:|:fset [h_loc;tmp_loc]) (I1:|:I2) ('unit))) (ret_both (tt : 'unit)) in
    solve_lift h : both (L1 :|: L2 :|: fset [h_loc;tmp_loc]) (I1 :|: I2) (t_Hash).
Fail Next Obligation.

Definition h_loc : Location :=
  (t_Hash;3%nat).
Equations compress {L1 : {fset Location}} {L2 : {fset Location}} {I1 : Interface} {I2 : Interface} (block : both L1 I1 (t_Block)) (h_in : both L2 I2 (t_Hash)) : both (L1 :|: L2 :|: fset [h_loc;s_loc;tmp_loc;h_loc;tmp_loc]) (I1 :|: I2) (t_Hash) :=
  compress block h_in  :=
    letb s := schedule block in
    letb h loc(h_loc) := shuffle s h_in in
    letb _ := foldi_both_list (f_into_iter (Build_t_Range (f_start := ret_both (0 : int32)) (f_end := ret_both (8 : int32)))) (fun i =>
      ssp (fun _ =>
        assign todo(term) : both (*4*)(L1:|:L2:|:fset [h_loc;h_loc;s_loc;tmp_loc]) (I1:|:I2) ('unit))) (ret_both (tt : 'unit)) in
    solve_lift h : both (L1 :|: L2 :|: fset [h_loc;s_loc;tmp_loc;h_loc;tmp_loc]) (I1 :|: I2) (t_Hash).
Fail Next Obligation.

Definition h_loc : Location :=
  (t_Hash;4%nat).
Definition last_block_loc : Location :=
  (t_Block;5%nat).
Definition last_block_len_loc : Location :=
  (uint_size;6%nat).
Definition pad_block_loc : Location :=
  (t_Block;7%nat).
Equations hash {L1 : {fset Location}} {I1 : Interface} (msg : both L1 I1 (t_Seq (t_U8))) : both (L1 :|: fset [h_loc;last_block_loc;last_block_len_loc;pad_block_loc;h_loc;s_loc;tmp_loc;h_loc;tmp_loc]) I1 (t_Sha256Digest) :=
  hash msg  :=
    letb h loc(h_loc) := v_HASH_INIT in
    letb last_block loc(last_block_loc) := impl__Block__new (ret_both (tt : 'unit)) in
    letb last_block_len loc(last_block_len_loc) := ret_both (0 : uint_size) in
    letb _ := foldi_both_list (f_into_iter (Build_t_Range (f_start := ret_both (0 : uint_size)) (f_end := impl_41__num_chunks msg v_BLOCK_SIZE))) (fun i =>
      ssp (fun _ =>
        letb '(block_len,block) := impl_41__get_chunk msg v_BLOCK_SIZE i in
        solve_lift (ifb block_len <.? v_BLOCK_SIZE
        then letb _ := assign todo(term) in
        letb _ := assign todo(term) in
        ret_both (tt : 'unit)
        else letb compress_input := impl__Block__from_seq block in
        letb _ := assign todo(term) in
        ret_both (tt : 'unit)) : both (*5*)(L1:|:L1:|:fset [h_loc;h_loc;h_loc;s_loc;tmp_loc]) (I1:|:I1) ('unit))) (ret_both (tt : 'unit)) in
    letb _ := assign todo(term) in
    letb len_bist := U64 (cast_int (WS2 := _) ((impl_41__len msg) .* (ret_both (8 : uint_size)))) in
    letb _ := ifb last_block_len <.? (v_BLOCK_SIZE .- v_LEN_SIZE)
    then letb _ := assign todo(term) in
    letb _ := assign todo(term) in
    ret_both (tt : 'unit)
    else letb pad_block loc(pad_block_loc) := impl__Block__new (ret_both (tt : 'unit)) in
    letb _ := assign todo(term) in
    letb _ := assign todo(term) in
    letb _ := assign todo(term) in
    ret_both (tt : 'unit) in
    solve_lift (impl__Sha256Digest__from_seq (impl__Hash__to_be_bytes h)) : both (L1 :|: fset [h_loc;last_block_loc;last_block_len_loc;pad_block_loc;h_loc;s_loc;tmp_loc;h_loc;tmp_loc]) I1 (t_Sha256Digest).
Fail Next Obligation.

Equations sha256 {L1 : {fset Location}} {I1 : Interface} (msg : both L1 I1 (t_Seq (t_U8))) : both (L1 :|: fset [h_loc;last_block_loc;last_block_len_loc;pad_block_loc;h_loc;s_loc;tmp_loc;h_loc;tmp_loc]) I1 (t_Sha256Digest) :=
  sha256 msg  :=
    solve_lift (hash msg) : both (L1 :|: fset [h_loc;last_block_loc;last_block_len_loc;pad_block_loc;h_loc;s_loc;tmp_loc;h_loc;tmp_loc]) I1 (t_Sha256Digest).
Fail Next Obligation.
