(* File automatically generated by Hacspec *)
From Hacspec Require Import Hacspec_Lib MachineIntegers.
From Coq Require Import ZArith.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.

Require Import Super.

Class t_ContextType Self := {
}.

Instance t_InitContextExtern_t_t_ContextType : t_ContextType t_InitContextExtern_t := {
}.

Instance t_ReceiveContextExtern_t_t_ContextType : t_ContextType t_ReceiveContextExtern_t := {
}.
