(* File automatically generated by Hacspec *)
From Hacspec Require Import Hacspec_Lib MachineIntegers.
From Coq Require Import ZArith.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

Definition trap : t_Never_t :=
  abort.

Require Import Alloc.

Require Import Alloc. (* as ToOwned *)

Require Import Alloc. (* as string *)

Require Import Alloc. (* as String *)

Require Import Alloc. (* as ToString *)

Require Import Alloc. (* as vec *)

Require Import Alloc. (* as Vec *)

Require Import Core.

Require Import Core. (* as convert *)

Require Import Core. (* as hash *)

Require Import Core. (* as marker *)

Require Import Core. (* as mem *)

Require Import Core. (* as num *)

Require Import Core.

Require Import Alloc. (* as collections *)

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

(*Not implemented yet? todo(item)*)

Require Import Concordium_prims.

Require Import Concordium_types.

Require Import Concordium_traits.

(*Not implemented yet? todo(item)*)

Require Import Concordium_contracts_common.

(*Not implemented yet? todo(item)*)

Require Import Hacspec_concordium_derive.
