(* File automatically generated by Hacspec *)
From Hacspec Require Import Hacspec_Lib MachineIntegers.
From Coq Require Import ZArith.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.

(*Not implemented yet? todo(item)*)

Definition test : int8 :=
  let acc := ((@repr WORDSIZE8 0)) : int8 in
  let acc := (f_fold (f_into_iter (Build_Range (@repr WORDSIZE8 1)(@repr WORDSIZE8 10))) acc (fun acc i =>
      acc.+i)) : int8 in
  acc.+(@repr WORDSIZE8 1).
