(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import ssrZ word.
From Jasmin Require Import word.

From Coq Require Import ZArith.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(*Not implemented yet? todo(item)*)

Require Import Hacspec_lib.

(*Not implemented yet? todo(item)*)

Require Import Schnorr.

Require Import Schnorr. (* as sample_uniform *)

Require Import Schnorr.

Notation t_public := (t_Q).

Notation t_public_key := ((t_Q × (t_G × t_G × t_Q × t_G))).

Program Definition p_i_init {L1 : {fset Location}} {I1 : Interface} (_ : both L1 I1 (unit)) : both (L1 :|: fset [commit_loc]) (I1) ((t_Q × (t_G × t_G × t_Q × t_G))) :=
  letb x := (sample_uniform) : both _ _ (t_G) in
  letb y := (v_ONE) : both _ _ (t_Q) in
  letb zkp := (fiat_shamir_run prod_b(x,y)) : both _ _ ((t_G × t_G × t_Q × t_G)) in
  prod_b(y,zkp).
Fail Next Obligation.

Notation t_N := (nat_mod 0x1a0111ea397fe69a4b1ba7b6434bacd764774b84f38512bf6730d2a0f6b0f6241eabfffeb153ffffb9feffffffffaaab).
Definition N {L : {fset Location}} {I : Interface} : both L I (t_N) -> both L I (t_N) :=
  id.

Notation t_pid := (t_N).

Require Import Std. (* as HashMap *)

Notation t_public_keys := (t_HashMap (t_N) ((t_Q × (t_G × t_G × t_Q × t_G))) (t_RandomState)).

Program Definition p_i_construct {L1 : {fset Location}} {I1 : Interface} (m : both L1 I1 (t_HashMap (t_N) ((t_Q × (t_G × t_G × t_Q × t_G))) (t_RandomState))) : both (L1) (I1) (unit) :=
  tt.
Fail Next Obligation.

Program Definition p_i_vote {L1 : {fset Location}} {I1 : Interface} (v : both L1 I1 ('bool)) : both (L1) (I1) (t_Q) :=
  v_ONE.
Fail Next Obligation.

Program Definition exec {L1 : {fset Location}} {I1 : Interface} (v : both L1 I1 ('bool)) : both (L1 :|: fset [commit_loc]) (I1) (t_Q) :=
  letb x := (sample_uniform) : both _ _ (t_G) in
  letb y := (v_ONE) : both _ _ (t_Q) in
  letb zkp := (fiat_shamir_run prod_b(x,y)) : both _ _ ((t_G × t_G × t_Q × t_G)) in
  p_i_vote v.
Fail Next Obligation.
