(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import ssrZ word.
From Jasmin Require Import word.

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
   Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

(** Tool: export_name _ 
Tool: no_std _ 
Tool: feature _ register_tool
Tool: register_tool _ _hax **)
Require Import Concordium_std.
Export Concordium_std.

(** Tool: export_name _ 
Tool: no_std _ 
Tool: feature _ register_tool
Tool: register_tool _ _hax **)
Require Import SeekFrom.
Export SeekFrom.

(** Tool: export_name _ 
Tool: no_std _ 
Tool: feature _ register_tool
Tool: register_tool _ _hax **)
Require Import ContractState.
Export ContractState.

(** Tool: export_name _ 
Tool: no_std _ 
Tool: feature _ register_tool
Tool: register_tool _ _hax **)
Require Import Logger.
Export Logger.

(** Tool: export_name _ 
Tool: no_std _ 
Tool: feature _ register_tool
Tool: register_tool _ _hax **)
Require Import trap.
Export trap.
