(* File automatically generated by Hacspec *)
From Hacspec Require Import Hacspec_Lib.

From Coq Require Import ZArith.
Import List.ListNotations.
Open Scope Z_scope.
Open Scope bool_scope.

Require Import Lia.
Require Import Coq.Logic.FunctionalExtensionality.
Require Import Sumbool.

From mathcomp Require Import fintype.

From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset fmap.

From mathcomp Require Import ssrZ word.
From Jasmin Require Import word.

From Coq Require Import ZArith List.
Import ListNotations.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Declare Scope hacspec_scope.

Open Scope list_scope.
Open Scope hacspec_scope.
Open Scope nat_scope.

(* Require Import Hacspec_Lib_Comparable. *)

Import choice.Choice.Exports.

Require Import Core.
Export Core.

Require Import Hacspec_lib.
Export Hacspec_lib.

Inductive random_state :=
  t_RandomState.
Definition t_HashMap A B (_ : random_state) := chMap A B.

Axiom insert : forall {L1 L2 L3 I1 I2 I3 A B}, both L1 I1 (t_HashMap A B t_RandomState) -> both L2 I2 A -> both L3 I3 B -> both (L1 :|: L2 :|: L3) (I1 :|: I2 :|: I3) (t_Option B × t_HashMap A B t_RandomState).
Axiom get :  forall {L1 L2 I1 I2 A B}, both L1 I1 (t_HashMap A B t_RandomState) -> both L2 I2 A -> both (L1 :|: L2) (I1 :|: I2) (t_Option B).

Axiom new :  forall {L I A B}, both L I (t_HashMap A B t_RandomState).

