[package]
name = "hacspec-linalg"
version = "0.1.0"
authors = ["Rasmus Kirk <mail@rasmuskirk.com>"]
edition = "2018"

[lib]
path = "src/linalg.rs"

[dependencies]
hacspec-lib.workspace = true

[dev-dependencies]
hacspec-dev.workspace = true
quickcheck = "1"
nalgebra = "0.31"