[package]
name = "hmac"
version = "0.1.0"
authors = ["Franziskus Kiefer <franziskuskiefer@gmail.com>"]
edition = "2021"

[lib]
path = "src/hmac.rs"

[dependencies]
sha256 = { path = "../sha256-rust" }

[dev-dependencies]
hex = "0.4"
